version: "3.9"
services:
  django:
    build: 
      context: .
      args: 
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${DEV_GID:-1000}
    user: ${DEV_UID:-1000}:${DEV_GID:-1000}
    tty: true
    ports:
      - 5000:5000
    volumes:
      - .:/project
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-main}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-userpass}
    ports:
      - 3306:3306