# Generated by Django 4.0.4 on 2022-05-05 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_Initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time',
        ),
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='email',
            field=models.CharField(default='workata@gmail.com', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Kobierzyce Cup', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='phone_number',
            field=models.CharField(default='+48123456789', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 18, 22, 2, 840367)),
            preserve_default=False,
        ),
    ]
