# Generated by Django 4.0.4 on 2022-05-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_ceo',
            new_name='ceo',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='name',
        ),
    ]
