# Generated by Django 4.0.4 on 2022-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_club_ceo_club_ceo_rename_club_name_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.CharField(default='karateclub@gmail.com', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.TextField(default='5CABE3'),
        ),
    ]
