# Generated by Django 4.0.4 on 2022-05-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staff_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='parent_duel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.duel'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='participant_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_one', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='participant_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weiner', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.TextField(default='CA4B66'),
        ),
    ]
